apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Name }}
spec:
  type: ClusterIP # LoadBalancer
  selector:
    app: {{ .Release.Name }}-web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
  namespace: {{ .Release.Name }}
spec:
  type: ClusterIP # LoadBalancer
  selector:
    app: {{ .Release.Name }}-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cqf
  namespace: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-cqf
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080