apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: demo
data:
  api-local.yml: |
    api:
      fhir-server-store: http://demo-cqf/fhir
      auth-jwks-url: https://oauth.default/auth/realms/NHSNLink/protocol/openid-connect/certs #auth-jwks-url: https://oauth.nhsnlink.org/auth/realms/NHSNLink/protocol/openid-connect/certs
      downloader: com.lantanagroup.nandina.api.download.MeasureReportDownloader
      sender: com.lantanagroup.nandina.api.download.MeasureReportSender
      send-url: https://0047-sdc-phi.leidosweb.net/hapi-fhir-jpaserver/fhir/Bundle
      measures:
        - id: COVIDMin
          url: https://ehr-test.nhsnlink.org/fhir/Bundle/COVIDMin # 
          name: COVIDMin
        - id: MedAdmin
          url: https://ehr-test.nhsnlink.org/fhir/Bundle/NHSNMedicationAdministration # 
          name: MedAdmin
        - id: SNF
          url: https://ehr-test.nhsnlink.org/fhir/Bundle/COVID19AdmissionsFromSNF # 
          name: SNF
        - id: RiskFactors
          url: https://ehr-test.nhsnlink.org/fhir/Bundle/COVID19PRF # 
          name: RiskFactors
      query:
        mode: Local
    query:
      fhir-server-base: https://fhir-ehr-code.cerner.com/r4/ec2458f2-1e24-41c8-b71b-0e701af7583d
      query-auth:
        auth-mode: OAuth2
        username: 317986e4-e608-4d1c-9b84-da6146790730
        password: VStlal_dOB3LDEgG93wx0ZEPDURZWamD
        scopes: system/AllergyIntolerance.read system/Condition.read system/Observation.read system/Encounter.read system/Patient.read system/MedicationRequest.read system/Procedure.read
        token-url: https://authorization.cerner.com/tenants/ec2458f2-1e24-41c8-b71b-0e701af7583d/protocols/oauth2/profiles/smart-v1/token